environment: uat
replicaCount: 2
route:
  host: bff-retail-uat.apps.ocp-uat.meridian.internal
networkPolicy:
  allowFromNamespaces:
    - cswt-uat
    - cswt-uat-perf
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
