apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "txn-posting-service.fullname" . }}-env
  labels:
    {{- include "txn-posting-service.labels" . | nindent 4 }}
data:
  {{- $env := dict }}
  {{- range $k, $v := .Values.env }}
  {{- $_ := set $env $k (tpl (toString $v) $) }}
  {{- end }}
  {{- range $k, $v := $env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  env.json: |
    {{- $env | toPrettyJson | nindent 4 }}
