# Beacon sandbox account. The only environment that exists. Backend is the landing zone state
# bucket; CHANGEME values until BCN-207 provides the real names, at which point this file is
# regenerated by the landing zone pipeline and the placeholders go away.
terraform {
  required_version = ">= 1.5.0, < 2.0.0"
  backend "s3" {
    bucket         = "CHANGEME-meridian-tfstate-beacon-sbx"
    key            = "platform-tooling/notifications-lambda/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "CHANGEME-meridian-tfstate-lock"
    encrypt        = true
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.31.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  assume_role {
    role_arn = "arn:aws:iam::000000000000:role/CHANGEME-beacon-sbx-terraform"
  }
  default_tags {
    tags = {
      "meridian:repo" = "angular-migration-demo-estate/platform-tooling/terraform"
    }
  }
}

module "notifications_target" {
  source      = "../../modules/notifications-lambda"
  environment = "sbx"
  name        = "mtb-sbx-beacon-notifications-target"
  tags = {
    "meridian:ticket" = "BCN-201"
  }
}

output "topic_arn" {
  value = module.notifications_target.topic_arn
}
