apiVersion: v2
name: business-web
description: Meridian Business (commercial banking portal). Static Angular bundle served by unprivileged nginx on OpenShift.
type: application
version: 1.12.0
appVersion: "2024.10.1"
kubeVersion: ">=1.24.0-0"
home: https://confluence.meridian.internal/display/PLAT/Helm+charts
sources:
  - https://bitbucket.meridian.internal/projects/CSWT/repos/business-web
maintainers:
  - name: Platform Engineering
    email: platform-engineering@example.com
  - name: business-web
    email: business-web@example.com
annotations:
  meridian.bank/ticket-key: MBZ
  meridian.bank/pipeline: meridianNodePipeline
  meridian.bank/node-version: "14.21.3"
