# dev: shared developer namespace cswt-dev, one replica, no autoscaling, verbose everything.
environment: dev
replicaCount: 1
image:
  pullPolicy: Always
route:
  host: business-web-dev.apps.ocp-dev.northgate.internal
env:
  environment: dev
  apiBaseUrl: https://bff-business-dev.apps.ocp-dev.northgate.internal/api/v1
  idpIssuer: https://keystone-dev.apps.ocp-dev.northgate.internal/realms/northgate
  lanternCollectorUrl: https://lantern-collector-dev.apps.ocp-dev.northgate.internal/v1/events
  lanternSiteKey: CHANGEME-lantern-site-key-dev
  featureFlagsUrl: https://semaphore-dev.apps.ocp-dev.northgate.internal/api/flags
  sessionTimeoutMinutes: 60
nginx:
  extraCspConnectSrc:
    - https://bff-business-dev.apps.ocp-dev.northgate.internal
    - https://lantern-collector-dev.apps.ocp-dev.northgate.internal
    - https://keystone-dev.apps.ocp-dev.northgate.internal
podDisruptionBudget:
  enabled: false
networkPolicy:
  allowFromNamespaces:
    - cswt-dev-tools
