apiVersion: v1
kind: Service
metadata:
  name: {{ include "keystone-web.fullname" . }}
  labels:
    {{- include "keystone-web.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "keystone-web.fullname" . }}-tls
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "keystone-web.selectorLabels" . | nindent 4 }}
