---
- name: restart splunkforwarder
  ansible.builtin.service:
    name: SplunkForwarder
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
