apiVersion: v2
name: retail-web
description: Meridian Online (retail internet banking). Static Angular bundle served by unprivileged nginx on OpenShift.
type: application
version: 1.18.0
appVersion: "2024.11.2"
kubeVersion: ">=1.24.0-0"
home: https://confluence.meridian.internal/display/PLAT/Helm+charts
sources:
  - https://bitbucket.meridian.internal/projects/CSWT/repos/retail-web
maintainers:
  - name: Platform Engineering
    email: platform-engineering@example.com
  - name: retail-digital
    email: retail-digital@example.com
annotations:
  meridian.bank/ticket-key: MOL
  meridian.bank/pipeline: meridianNodePipeline
  meridian.bank/node-version: "16.20.2"
