environment: dev
replicaCount: 1
image:
  pullPolicy: Always
route:
  enabled: false
env:
  SPRING_PROFILES_ACTIVE: openshift,dev
  LOG_SAMPLING: "off"
podDisruptionBudget:
  enabled: false
networkPolicy:
  allowFromNamespaces:
    - cswt-dev
    - cswt-dev-tools
